### ISSUE TITLE
Format code snippet in `tools` section.

### ISSUE THREAD

**Issue by JamesPHoughton** [Watts-Lab/deliberation-website#12]
In the "tools" tab we have a `yaml` code snippet for the experiment manifest that looks a bit out of place without better formatting:

<img width="645" alt="image" src="https://github.com/Watts-Lab/deliberation-website/assets/4304478/e9b7cd42-71a8-4175-892e-dfc2446a2112">

I'm not sure what markdown renderer Jekyll is using, but would be good to format the code block in a similar way to how github does, eg. with a grey background, maybe a bit of indentation, and if possible, syntax highlighting.

```yaml
- name: baseline_control
  desc: Listening study baseline condition
  playerCount: 2
  assignPositionsBy: random
  gameStages:
    - name: Intro
      type: prompt
      duration: 45
      elements:
        - intro_no_training.md
        - type: submitButton

    - name: Attitude Presurvey
      duration: 120
      elements:
        - urban_unrest_survey.md
        - type: submitButton

    - name: Discussion
      duration: 600
      chatType: video
      elements:
        - type: prompt
          file: urban_unrest_discussion.md
        - type: prompt
          file: instructions_listener.md
          showToPositions:
            - 0
        - type: prompt
          file: projects/weinstein_listening/instructions_speaker.md
          showToPositions:
            - 1
```

Ideally this should be done without too much change to the markdown file itself.
